### ISSUE TITLE
Utils下找不到SelfAttentionBlock

### ISSUE THREAD

**Issue by wk19990213** [CVIU-CSU/HRDecoder#5]
![image](https://github.com/user-attachments/assets/5d7434fa-d407-4685-994c-44ef14bcdb0c)
在Utils下确实找不到SelfAttentionBlock这个模块，有些疑惑，希望能得到解答

**Comment by gitdzy** [comment]
感谢你指出了这个问题，我在上传代码的时候主要上传了自己方法相关的部分，其他部分的代码没有上传。

目前我在github上已经添加了这几个文件。如果还有文件缺失的问题，欢迎在issue中指出，我会进行补全。

当然，你也可以把mmseg-0.16.0作为主分支，然后把我的代码合并到主分支，这样也能补全缺失的文件。

希望能够帮到你。

**Comment by wk19990213** [comment]
> 感谢你指出了这个问题，我在上传代码的时候主要上传了自己方法相关的部分，其他部分的代码没有上传。
> 
> 目前我在github上已经添加了这几个文件。如果还有文件缺失的问题，欢迎在issue中指出，我会进行补全。
> 
> 当然，你也可以把mmseg-0.16.0作为主分支，然后把我的代码合并到主分支，这样也能补全缺失的文件。
> 
> 希望能够帮到你。
感谢，祝万事胜意，多发paper
